FEATURE_HIDE_UNVERIFIED_FROM_SEARCH = False
FEATURE_BLOCK_DISABLED_USERS = False
FEATURE_AUTHENTICATE_KYC_UPLOAD = True
FEATURE_ADMIN_LOGOUT = True
FEATURE_KYC_RETENTION_CLEANUP = False
FEATURE_KYC_REUPLOAD_POLICY = True
FEATURE_ENFORCE_VERIFIED_FOR_HIRE_MESSAGE = False
